### ISSUE TITLE
Check NFC Setting

### ISSUE THREAD

**Issue by reznikovt** [vcu-cmsc355-f17/android-app-purple-platypi#17]
As a user, I would like to make sure my NFC settings are on, so that when another device is held up to mine I can receive data.

Note that there is no Espresso scenario outlined in code for this User Story. Per Dr. Damevski, NFC interacts with elements of Android interface not easily handled by Espresso testing. Please see attached video for full functionality and email leea3@vcu.edu with any questions or if video is not available. 
******************

**Scenario 1: NFC Settings Off Confirmation 1**
Given I am on the home screen and my NFC setting is off,
- When I press the Connect button
  - Then I am taken to the Android settings menu
  - Then I should see a Toast stating "NFC must be turned on by User in Settings"

****************

**Scenario 2: NFC Settings On Confirmation**
Given I am on the home screen and my NFC setting is on,
- When I press the Connect button
  - Then I am taken to the ConnectActivity screen
  - Then I should see a Toast stating "NFC is on, you're good to go!"

**********

**Scenario 3: NFC Settings Off Confirmation 2**
Given I am on the connect screen and NFC is off,
- When I click the Send File button
  - Then I am taken to the Android settings menu
  - Then I should see a Toast stating "Please enable NFC."

**Comment by Leea3** [comment]
Check NFC Settings Video:
https://www.dropbox.com/s/o1isgjgqhlpxp1e/Check_NFC_Settings.MOV?dl=0
