### ISSUE TITLE
NFC Connection Functionality

### ISSUE THREAD

**Issue by ShaneGifford** [vcu-cmsc355-f17/android-app-purple-platypi#5]
As a celebrity, I want to be able to securely and quickly share my relevant contact information with necessary business partners, so that my personal information only goes into the right hands.

Note that there is no Espresso scenario outlined in code for this User Story. Per Dr. Damevski, NFC interacts with elements of Android interface not easily handled by Espresso testing. Please see attached video for full functionality and email leea3@vcu.edu with any questions or if video is not available.

**Scenario 1: Confirm NFC is on For Both Devices**
Given I am on the App Home screen,
Given that NFC is turned on for the device,
- When I press the Connect button,
  - Then the screen should change to the Connect Activity screen
  - Then a Toast will appear stating "NFC is on, you're good to go!

**Scenario 2: Confirm That Device 1 Beams Contact to Device 2**
Given I am on the Connect Activity screen
Given that NFC is on for both devices
- When Device 1 attempts to send a Contact
  - Then Device 1 should display text stating "Touch to beam." with an animation
  - Then Device 1 returns to the Connect Activity screen

**Scenario 3: Confirm That Device 2 Receives Contact From Device 1**
Given I am on the Connect Activity screen
Given that NFC is on for both devices
- When Device 1 beams a Contact to Device 2
  - Then a Toast is displayed on Device 2 stating "NFC is on, you're good to go!" (confirming NFC connection between the two devices)
  - Then a Toast is displayed with the information associated with the newly acquired Contact
- When I press the back button,
  - Then I am taken to the Home Activity screen
- When I press the Contacts button,
  - Then the newly acquired Contact is displayed in the Contacts Activity screen
- When I click on the newly acquired Contact,
  - Then the information associated with the newly acquired Contact is the same as displayed by the previous Toast in the Connect Activity screen

**Comment by Leea3** [comment]
NFC Connection Functionality Video:
https://www.dropbox.com/s/whgz4eyg1g4s5v5/NFC_Demo.mp4?dl=0
